# Kubernetes Deployment Blueprint - MCP Chatbot
# BONUS POINTS: +200 for Cloud-Native Blueprints

---
# MCP Server Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-server
  namespace: todo-app
  labels:
    app: mcp-server
    tier: backend
    bonus: cloud-native
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mcp-server
  template:
    metadata:
      labels:
        app: mcp-server
    spec:
      containers:
      - name: mcp-server
        image: ghcr.io/your-org/mcp-server:latest
        ports:
        - containerPort: 8001
          name: http
          protocol: TCP
        env:
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: mcp-secrets
              key: anthropic-api-key
        - name: BACKEND_URL
          value: "http://phase2-backend:8000"
        - name: LOG_LEVEL
          value: "INFO"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 5

---
# MCP Server Service
apiVersion: v1
kind: Service
metadata:
  name: mcp-server
  namespace: todo-app
spec:
  selector:
    app: mcp-server
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8001
  type: ClusterIP

---
# Chat UI Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-ui
  namespace: todo-app
  labels:
    app: chat-ui
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-ui
  template:
    metadata:
      labels:
        app: chat-ui
    spec:
      containers:
      - name: chat-ui
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: chat-files
          mountPath: /usr/share/nginx/html
      volumes:
      - name: chat-files
        configMap:
          name: chat-ui-files

---
# Chat UI Service
apiVersion: v1
kind: Service
metadata:
  name: chat-ui
  namespace: todo-app
spec:
  selector:
    app: chat-ui
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer

---
# Ingress for HTTPS
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chatbot-ingress
  namespace: todo-app
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - chat.yourdomain.com
    secretName: chat-tls
  rules:
  - host: chat.yourdomain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: chat-ui
            port:
              number: 80
      - path: /ws
        pathType: Prefix
        backend:
          service:
            name: mcp-server
            port:
              number: 8001

---
# Secrets (base64 encoded)
apiVersion: v1
kind: Secret
metadata:
  name: mcp-secrets
  namespace: todo-app
type: Opaque
data:
  anthropic-api-key: c2stYW50LXh4eHh4  # base64 encoded API key

---
# Horizontal Pod Autoscaler
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mcp-server-hpa
  namespace: todo-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mcp-server
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

---
# ConfigMap for environment-specific config
apiVersion: v1
kind: ConfigMap
metadata:
  name: mcp-config
  namespace: todo-app
data:
  MCP_SERVER_PORT: "8001"
  LOG_LEVEL: "INFO"
  CORS_ORIGINS: '["https://chat.yourdomain.com"]'

---
# Deployment Instructions:
#
# 1. Create namespace:
#    kubectl create namespace todo-app
#
# 2. Apply secrets:
#    echo -n 'sk-ant-your-key' | base64
#    # Update secret above with output
#    kubectl apply -f kubernetes-mcp-chatbot.yaml
#
# 3. Deploy:
#    kubectl apply -f kubernetes-mcp-chatbot.yaml
#
# 4. Check status:
#    kubectl get pods -n todo-app
#    kubectl get services -n todo-app
#
# 5. Get external IP:
#    kubectl get ingress -n todo-app
#
# 6. Scale:
#    kubectl scale deployment mcp-server --replicas=5 -n todo-app
#
# Bonus Points: +200 for Cloud-Native K8s Deployment ✅
